src/candidates/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^districts', views.districts, name='districts'),
    url(r'^map', views.map, name='map'),
    url(r'^zoomed', views.zoomed, name='zoomed'),
    url(r'^(?P<id>[0-9]+)/$', views.results, name='results'),
]

src/climatevote/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('candidates.urls')),
]

src/candidates/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class District(models.Model):
    zip_code = models.IntegerField()
    congressional_district = models.IntegerField()

    def __str__(self):
        return self.zip_code

class CongressMan(models.Model):
    name = models.CharField(max_length=140)
    stance = models.CharField(max_length=1)
    district = models.IntegerField()
    party = models.CharField(max_length=15)
    incumbent = models.CharField(max_length=3)
    url = models.CharField(max_length=200)
    img_url = models.CharField(max_length=400)

    def __str__(self):
        return self.name

src/candidates/forms.py
from django import forms

class zip_number(forms.Form):
    zip_code = forms.IntegerField(label='zip_code')

src/candidates/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.shortcuts import redirect

from forms import zip_number
from models import District, CongressMan
from django.views import generic
from django.shortcuts import get_object_or_404

def home(request):
    if request.method == 'POST':
        form = zip_number(data=request.POST)

        if form.is_valid():
            zip_c = request.POST.get('zip_code', '')

            for obj in District.objects.all():
                if obj.zip_code == int(zip_c):
                    print "found"

                    for congress_obj in CongressMan.objects.all():
                        if obj.congressional_district == congress_obj.district:

                            if (congress_obj.party == "D"):
                                party = "Democrat"
                            elif (congress_obj.party == "R"):
                                party = "Republic"
                            else:
                                party = "Independent"

                            if (congress_obj.stance == "F"):
                                stance = "Supports Action Against Climate Change"
                            else:
                                stance = "Climate Change Denier"

                            url = congress_obj.url
                            img_url = congress_obj.img_url

                            return render(request,'districts.html', {
                            'number': "You're in Congressional District " + str(obj.congressional_district),
                            'congressman': congress_obj.name,
                            'party': party,
                            'stance': stance,
                            'url': url,
                            'img_url': img_url })

    else:
        form = zip_number()

    return render(request, 'home.html', {'form': form})

def districts(request):
	return render(request, 'districts.html', {'number': ''})

def map(request):
    return render(request, 'map.html',{})

def zoomed(request):
    return render(request, 'zoomed.html', {'number': ''}) 

def about(request):
	return render(request, 'about.html', {})

def contact(request):
	return render(request, 'contact.html', {})

def results(request, id):
    congressman = get_object_or_404(CongressMan, district=id)

    if (congressman.party == "D"):
       party = "Democrat"
    elif (congressman.party == "R"):
        party = "Republic"
    else:
        party = "Independent"

    if (congressman.stance == "F"):
        stance = "Supports Action Against Climate Change"
    else:
        stance = "Climate Change Denier"

    url = congressman.url
    img_url = congressman.img_url

    print img_url

    return render(request, 'districts.html', {'congressman': congressman,
        'stance': stance,
        'url' : url,
        'party' : party,
        'number' : "You're in Congressional District " + str(congressman.district),
        'img_url' : img_url})

src/candidates/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}

About

{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">

{% endblock %}

{% block content %}

<h1 class="title"> About </h1>

<div class="about-text">
	<p>Inspired by Bill Nye's new Netflix show "Bill Nye Saves the World"</p>

	<p>We hope to give voters who are concerned with climate change an easier way of finding out which Californian Representatives are climate change supporters. By presenting infomation about candidates' stances, voters can be more informed about their decisions. </p>

	<p>By: Benson Gao, Adam Kabbara, Julio Sandino</p>

	<p>At BeachHacks 2017</p>
</div>

{% endblock %}

src/candidates/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>

<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
{% block style %}
{% endblock %}


<!-- Jquery CDN -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link rel="icon" href="{% static 'img/favicon.ico' %}">

<script src="https://use.fontawesome.com/023ea142c2.js"></script>
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}" style="font-size: 1.5em; font-family: "Helvetica Neue";">
          <i class="fa fa-globe title_icon" aria-hidden="true" style="color:white"></i>
          Climate Vote</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="cool-link"><a class = "link" href="{% url 'home' %}">HOME</a></li>
            <li><a class = "link" href="{% url 'about' %}">ABOUT</a></li>
            <li><a class = "link" href="{% url 'map' %}">MAP</a></li>
            <li><a class = "link" href="{% url 'contact' %}">CONTACT</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

{% block content %}
{% endblock %}

	<footer class="footer">
      <div class="container">
        <p class="text-muted">Made by Benson Gao, Adam Kabbara, Julio Sandino @BeachHacks 2017</p>
      </div>
    </footer>

</body>
</html>

src/candidates/templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}

Contact

{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endblock %}


{% block content %}

<h1 class="title"> Contact Us </h1>

<div class="form-container">
	<form class="form-horizontal">
		<div class="input-group">
		    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		    <input id="email" type="text" class="form-control" name="email" placeholder="Email">
		</div>
		<div class="form-group">
		  	<div class="col-sm-offset-0 col-sm-12">
		  		<textarea class="form-control" rows="5" id="comment" placeholder="Comment"></textarea>
		  	</div>
		</div>
	  <div class="form-group"> 
	    <div class="col-sm-offset-0 col-sm-10">
	      <button type="submit" class="btn btn-default">Submit</button>
	    </div>
	  </div>
	</form>
</div>

{% endblock %}

src/candidates/templates/districts.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}

Districts

{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/districts.css' %}">

{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 col-lg-offset-3 col-md-offset-2 col-sm-offset-1"> 
            <div class="representative">
                <h1 class="title"> {{number}} </h1>
                <h2 class="name" align="center"> Current Representative: {{congressman}} </h2>
                <img src="{{img_url}}" alt={{congressman}}>
                <p class="information" align="center"><p>{{party}}</p>
                <p>{{stance}}</p>
                <a href={{url}}>More Policy Information</a></p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

src/candidates/templates/home.html
{% extends 'base.html' %}
{% load staticfiles%}

{% block style %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">


{% endblock %}

{% block title %}

Home

{% endblock %}

{% block content %}

<div class="banner">
    <img class="banner" src="{% static 'img/banner.png' %}">
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-lg-offset-2 col-md-offset-1">

            <h1 class="zip"> Enter your zip here! </h1>

            <div align="center" class="form-container">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <input placeholder="zip code" type="number" name="zip_code" required id="id_zip_code" class="zip-code"/>
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-lg-offset-2 col-md-offset-1">

                <p class="home-text">
                    Climate change is a serious issue that our planet is facing now. If we don't take swift and decisive action, there will be serious consequences for life as we know it. However, there are many climate change deniers that are impeding progress in this critical field. Most notably, representatives in government halt legislation necessary for protecting our environment. This tool can help in determining which representatives are in support of stopping climate change.
                </p>
        </div>    
    </div>
</div>

{% endblock %}

src/candidates/templates/specific_district.html
<h1>{{ congressman.name }}</h1>

<ul>
    {{ congressman.district }}
</ul>